services:
  backupcenter:
    container_name: backupcenter

    build:
      context: .
      dockerfile: docker/Dockerfile

    image: backupcenter:dev

    ports:
      - "8085:80"

    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./updates:/var/www/html/updates
      - ./logs:/var/log/supervisor

    restart: unless-stopped